import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Notion Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="h-screen overflow-hidden">

          <Header />
          <div className="flex h-[calc(100vh-64px)]">
            <Sidebar />
            <div className="flex-1 p-4 bg-slate-100 overflow-y-scroll">
              {children}
            </div>
          </div>
          <Toaster position='top-center' />
        </body>
      </html>
    </ClerkProvider>
  );
}
